# Generated by Django 4.2.30 on 2026-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='reviews.dish', verbose_name='Избранные блюда'),
        ),
    ]
