# Generated by Django 4.2.30 on 2026-07-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_userprofile_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='in_wishlist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор обзора'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Описание и впечатление'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фотография блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Заведение / Ресторан'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка (от 1 до 5)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название блюда'),
        ),
    ]
