# Generated by Django 4.2.30 on 2026-07-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_dish_options_remove_dish_in_wishlist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
